version: '3.8'

services:
  news-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    # For development with hot-reload, uncomment these lines:
    # volumes:
    #   - ./src:/app/src
    #   - ./public:/app/public
    # command: npm run dev
